######################################################################
# Automatically generated by qmake (3.0) mer. janv. 6 21:42:02 2016
######################################################################

TEMPLATE = app
TARGET = NoeudThor
INCLUDEPATH += .

# Input
HEADERS += ../Client/client.h noeudthor.h ../Trame/trame.h 
SOURCES += main.cpp noeudthor.cpp ../Trame/trame.cpp
