######################################################################
# Automatically generated by qmake (3.0) mer. janv. 6 21:44:03 2016
######################################################################

TEMPLATE = app
TARGET = ServeurCentral
INCLUDEPATH += .

# Input
HEADERS += ../Client/client.h serveurcentral.h ../Trame/trame.h
SOURCES += main.cpp serveurcentral.cpp ../Trame/trame.cpp
