######################################################################
# Automatically generated by qmake (3.0) dim. janv. 3 13:27:27 2016
######################################################################

TEMPLATE = app
TARGET = ServeurCentral
INCLUDEPATH += .

# Input
HEADERS += ../Client/client.h serveurcentral.h ../Trame/trame.h
SOURCES += main.cpp serveurcentral.cpp ../Trame/trame.cpp
