######################################################################
# Automatically generated by qmake (3.0) dim. janv. 3 13:28:44 2016
######################################################################

TEMPLATE = app
TARGET = SecureNodeListProvider
INCLUDEPATH += .

# Input
HEADERS += ../Client/client.h securenodelistprovider.h ../Trame/trame.h
SOURCES += main.cpp securenodelistprovider.cpp ../Trame/trame.cpp
