######################################################################
# Automatically generated by qmake (3.0) mer. janv. 6 21:45:31 2016
######################################################################

TEMPLATE = app
TARGET = SecureNodeListProvider
INCLUDEPATH += .

# Input
HEADERS += ../Client/client.h securenodelistprovider.h ../Trame/trame.h
SOURCES += main.cpp securenodelistprovider.cpp ../Trame/trame.cpp
