######################################################################
# Automatically generated by qmake (2.01a) mar. déc. 29 19:52:25 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
QT += network
