######################################################################
# Automatically generated by qmake (2.01a) mer. déc. 30 15:40:57 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Tslot.h
SOURCES += main.cpp Tslot.cpp
QT += network
