######################################################################
# Automatically generated by qmake (2.01a) mar. déc. 29 14:25:08 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fusionneur.h task.h timertoken.h
SOURCES += fusionneur.cpp main.cpp task.cpp timertoken.cpp
QT += network
