######################################################################
# Automatically generated by qmake (3.0) dim. janv. 3 13:23:31 2016
######################################################################

TEMPLATE = app
TARGET = NoeudThor
INCLUDEPATH += .

# Input
HEADERS += ../Client/client.h noeudthor.h ../Trame/trame.h
SOURCES += main.cpp noeudthor.cpp ../Trame/trame.cpp
